version: '3.7'

services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - ghost-db
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__database: ghost-dev-db
      database__connection__user: ghost-dev-user
      database__connection__password: abc123
      NODE_ENV: development
      GHOST_DEBUG: true
      LOG_lEVEL: error
      url: http://localhost:2368
    volumes:
      - ./src:/var/lib/ghost/content/themes/fluid

  ghost-db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ghost-dev-db
      MYSQL_USER: ghost-dev-user
      MYSQL_PASSWORD: abc123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ghost-db:/var/lib/mysql

volumes:
  ghost-db:
